name: Install
description: Checkouts the repo and installs dependencies

runs:
  using: 'composite'
  steps:
    # Install pnpm because it is not included in our container image
    - name: install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7

    - name: Install deps
      uses: cypress-io/github-action@v5
      with:
        runTests: false