name: Build with Attestation
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          mkdir -p dist
          echo "Hello World" > dist/output.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dist/output.txt

  # 调用 SLSA 生成器工作流
  generate-provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.9.0
    permissions:
      id-token: write  # SLSA 必须权限
      contents: read
      actions: none    # 显式禁止 actions 权限（解决冲突）
    needs: build       # 依赖 build 作业
    with:
      # 正确输入参数名：artifact_paths（而非 artifacts）
      artifact_paths: "dist/output.txt"
      upload_assets: true  # 注意 SLSA 使用下划线（_），而非连字符（-）
