name: Build with Attestation
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          mkdir -p dist
          echo "Hello World" > dist/output.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dist/output.txt

  # 新增独立作业，调用可重用工作流生成 SLSA Provenance
  generate-provenance:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # 必须权限
      contents: read
    needs: build       # 依赖 build 作业
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.9.0
    with:
      artifacts: "dist/output.txt"  # 从 build 作业生成的产物路径
      upload-assets: true
